nslookup icadmin011.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup icadmin012.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup icadmin014.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster150.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster151.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster152.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster153.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster154.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster155.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster156.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster157.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster158.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster159.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster160.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster162.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster163.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster164.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster165.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster166.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster167.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster168.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster169.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster170.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster171.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster172.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster173.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster174.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster175.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster176.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster177.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster178.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster179.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster181.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster182.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster183.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster184.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster185.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster186.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster187.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster188.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster189.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster190.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster191.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster192.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster193.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster194.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster195.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster196.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster197.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster198.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster199.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster200.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster201.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster202.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster204.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster205.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster206.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster207.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster208.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster209.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster210.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster211.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster212.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster213.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster214.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster215.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster216.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster218.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster219.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster220.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster221.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster222.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster223.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster224.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
nslookup iccluster225.iccluster.epfl.ch  | egrep '^Address: (.*)' | awk '{print $2;}' >> IPs.txt
