---
- name: Download the debian package to a temporary location
  ansible.builtin.get_url:
    url: https://github.com/ncabatoff/process-exporter/releases/download/v0.7.10/process-exporter_0.7.10_linux_amd64.deb
    dest: /tmp/process-exporter_0.7.10_linux_amd64.deb
    mode: 0644

- name: Install the debian package
  ansible.builtin.apt:
    deb: /tmp/process-exporter_0.7.10_linux_amd64.deb
    state: present
    update_cache: yes
