---
- name: Install the ingress-nginx Helm chart
  kubernetes.core.helm:
    name: ingress-nginx
    chart_repo_url: https://kubernetes.github.io/ingress-nginx
    chart_ref: ingress-nginx
    state: present
    wait: false
    update_repo_cache: true
    release_namespace: ingress-nginx
    create_namespace: true
    values:
      controller:
        kind: DaemonSet
        service:
          externalIPs:
            - "{{ nginx_ingress_controller_external_ip }}"
          type: NodePort
